#!/usr/bin/env bash
# Install Borg + wire incremental backups (timer + pacman hook).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OWNER="${SUDO_USER:-$USER}"
OWNER_HOME="$(getent passwd "$OWNER" | cut -d: -f6)"
ENV_DST="${OWNER_HOME}/.config/dotfiles/backup.env"
UNIT_DIR="${OWNER_HOME}/.config/systemd/user"
HOOK_DST="/etc/pacman.d/hooks/99-dotfiles-backup.hook"
WRAPPER="/usr/local/bin/dotfiles-backup"
BACKUP_SCRIPT="$ROOT/scripts/backup.sh"

log() { printf '==> %s\n' "$*"; }

if [[ "$(id -u)" -eq 0 && -n "${SUDO_USER:-}" ]]; then
  : # running via sudo is fine
elif [[ "$(id -u)" -eq 0 ]]; then
  log "Prefer: sudo -u $OWNER or run as normal user with sudo available"
fi

log "Installing borg"
sudo pacman -S --needed --noconfirm borg

install -d -m 755 \
  "${OWNER_HOME}/.config/dotfiles" \
  "${OWNER_HOME}/.local/state/dotfiles" \
  "${OWNER_HOME}/backups" \
  "$UNIT_DIR"

if [[ ! -f "$ENV_DST" ]]; then
  install -m 600 "$ROOT/configs/backup/backup.env.example" "$ENV_DST"
  # Fix HOME in example for this user
  sed -i "s|\\\$HOME|$OWNER_HOME|g" "$ENV_DST"
  chown "$OWNER:$OWNER" "$ENV_DST" 2>/dev/null || true
  log "Created $ENV_DST — set BORG_PASSPHRASE before first backup"
else
  log "Keeping existing $ENV_DST"
fi
chown -R "$OWNER:$OWNER" \
  "${OWNER_HOME}/.config/dotfiles" \
  "${OWNER_HOME}/.local/state/dotfiles" \
  "${OWNER_HOME}/backups" \
  "$UNIT_DIR" 2>/dev/null || true

sudo tee "$WRAPPER" >/dev/null <<EOF
#!/usr/bin/env bash
# Auto-generated by dotfiles install/backup.sh
set -euo pipefail
OWNER="${OWNER}"
HOME_DIR="${OWNER_HOME}"
SCRIPT="${BACKUP_SCRIPT}"
export HOME="\$HOME_DIR"
export USER="\$OWNER"
export DOTFILES_BACKUP_ENV="\$HOME_DIR/.config/dotfiles/backup.env"
export XDG_STATE_HOME="\$HOME_DIR/.local/state"
exec sudo -u "\$OWNER" -- "\$SCRIPT" "\$@"
EOF
sudo chmod 755 "$WRAPPER"

cat >"$UNIT_DIR/dotfiles-backup.service" <<EOF
[Unit]
Description=Dotfiles incremental Borg backup
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${BACKUP_SCRIPT} create timer
Nice=10
IOSchedulingClass=best-effort
IOSchedulingPriority=7
EOF

cat >"$UNIT_DIR/dotfiles-backup.timer" <<'EOF'
[Unit]
Description=Daily incremental Borg backup

[Timer]
OnCalendar=daily
Persistent=true
RandomizedDelaySec=30m

[Install]
WantedBy=timers.target
EOF

cat >"$UNIT_DIR/dotfiles-backup-prune.service" <<EOF
[Unit]
Description=Prune old Borg archives
After=dotfiles-backup.service

[Service]
Type=oneshot
ExecStart=${BACKUP_SCRIPT} prune
Nice=10
EOF

cat >"$UNIT_DIR/dotfiles-backup-prune.timer" <<'EOF'
[Unit]
Description=Weekly Borg prune

[Timer]
OnCalendar=weekly
Persistent=true
RandomizedDelaySec=1h

[Install]
WantedBy=timers.target
EOF

chown -R "$OWNER:$OWNER" "$UNIT_DIR"

if [[ "$(id -u)" -eq 0 ]]; then
  sudo -u "$OWNER" systemctl --user daemon-reload
  sudo -u "$OWNER" systemctl --user enable --now dotfiles-backup.timer
  sudo -u "$OWNER" systemctl --user enable --now dotfiles-backup-prune.timer
else
  systemctl --user daemon-reload
  systemctl --user enable --now dotfiles-backup.timer
  systemctl --user enable --now dotfiles-backup-prune.timer
fi

sudo mkdir -p /etc/pacman.d/hooks
sudo tee "$HOOK_DST" >/dev/null <<'EOF'
[Trigger]
Operation = Install
Operation = Upgrade
Operation = Remove
Type = Package
Target = *

[Action]
Description = Incremental Borg backup after package changes
When = PostTransaction
Exec = /usr/local/bin/dotfiles-backup create pacman
EOF

log "Backup stack ready"
echo
echo "Next steps:"
echo "  1. Edit passphrase:   $ENV_DST"
echo "  2. First full backup: $BACKUP_SCRIPT init"
echo "  3. Manual increment:  $BACKUP_SCRIPT create"
echo "  4. Auto: pacman hook + daily timer → same Borg repo"
echo
echo "Each 'create' stores only new/changed chunks (true incremental)."
